name: falco deploy to s3

on:
  push:
    branches: [main]
    paths:
      - 'falco/**'
  pull_request:
    branches: [main]

jobs:
    deploy-falco-rules:
        name: Deploy Falco rules to S3
        runs-on: ubuntu-latest

        env:
            AWS_REGION: ${{ secrets.AWS_REGION }}
            FALCO_BUCKET_NAME: ${{ secrets.FALCO_BUCKET_NAME }}
        
        steps:
            - name: checkout
              uses: actions/checkout@v4.2.2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4.2.1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Sync Falco rules to S3
              run: |
                aws s3 cp falco/custom_rules.yaml s3://$FALCO_BUCKET_NAME/custom_rules.yaml
                echo "Falco rules deployed to s3://$FALCO_BUCKET_NAME/custom_rules.yaml"